
source ~/code/config/vim/begin.vim

source ~/code/config/vim/vundle.vim
source ~/code/config/vim/python.vim
source ~/code/config/vim/keybind.vim
source ~/code/config/vim/misc.vim

source ~/code/config/vim/end.vim

